spring:
  datasource:
    url: jdbc:mysql://localhost:3334/test2017
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8889
mybatis:
  type-aliases-package: com.huwei.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false


